import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

country_df = pd.read_excel('country_economic_indicator.xls')
hd = country_df.columns
#print(hd)
#print(country_df.describe())

bhr_df = country_df[country_df.Country == 'Bahrain']
kwt_df = country_df[country_df.Country == 'Kuwait']
omn_df = country_df[country_df.Country == 'Oman']
sar_df = country_df[country_df.Country == 'Saudi Arabia']
#print(bhr_df.columns)

#plt.subplot(321)
plt.style.use('ggplot')
plt.plot(bhr_df.Year, bhr_df.electricity_consumption_kwh_perCapita)
plt.plot(kwt_df.Year, kwt_df.electricity_consumption_kwh_perCapita)
plt.plot(omn_df.Year, omn_df.electricity_consumption_kwh_perCapita)
plt.plot(bhr_df.Year, bhr_df.electricity_consumption_kwh_perCapita)
plt.plot(sar_df.Year, sar_df.electricity_consumption_kwh_perCapita)
plt.title("Electricity consumption kwh per capita ")
plt.xlabel("Year")
plt.ylabel("kwh")
plt.legend(["Bahrain", "Kuwait", "Oman", "Saudi Arabia"])
plt.show()

#plt.subplot(322)
plt.plot(bhr_df.Year, bhr_df.energy_use_in_kg_oil_per_capita)
plt.plot(kwt_df.Year, kwt_df.energy_use_in_kg_oil_per_capita)
plt.plot(omn_df.Year, omn_df.energy_use_in_kg_oil_per_capita)
plt.plot(bhr_df.Year, bhr_df.energy_use_in_kg_oil_per_capita)
plt.plot(sar_df.Year, sar_df.energy_use_in_kg_oil_per_capita)
plt.title("Energy generated kg oil per capita ")
plt.xlabel("Year")
plt.ylabel("kg")
plt.legend(["Bahrain", "Kuwait", "Oman", "Saudi Arabia"])
plt.show()

#plt.subplot(323)
plt.plot(bhr_df.Year, bhr_df.export_as_percent_of_GDP)
plt.plot(kwt_df.Year, kwt_df.export_as_percent_of_GDP)
plt.plot(omn_df.Year, omn_df.export_as_percent_of_GDP)
plt.plot(bhr_df.Year, bhr_df.export_as_percent_of_GDP)
plt.plot(sar_df.Year, sar_df.export_as_percent_of_GDP)
plt.title("Export as % of GDP")
plt.xlabel("Year")
plt.ylabel("Export %")
plt.legend(["Bahrain", "Kuwait", "Oman", "Saudi Arabia"])
plt.show()

#plt.subplot(324)
plt.plot(bhr_df.Year, bhr_df.GDP_growth_percent)
plt.plot(kwt_df.Year, kwt_df.GDP_growth_percent)
plt.plot(omn_df.Year, omn_df.GDP_growth_percent)
plt.plot(bhr_df.Year, bhr_df.GDP_growth_percent)
plt.plot(sar_df.Year, sar_df.GDP_growth_percent)
plt.title("Annual GDP growth %")
plt.xlabel("Year")
plt.ylabel("Growth %")
plt.legend(["Bahrain", "Kuwait", "Oman", "Saudi Arabia"])
plt.show()

#plt.subplot(325)
plt.plot(bhr_df.Year, bhr_df.gdp_perCapita_USD)
plt.plot(kwt_df.Year, kwt_df.gdp_perCapita_USD)
plt.plot(omn_df.Year, omn_df.gdp_perCapita_USD)
plt.plot(bhr_df.Year, bhr_df.gdp_perCapita_USD)
plt.plot(sar_df.Year, sar_df.gdp_perCapita_USD)
plt.title("GDP per capita $")
plt.xlabel("Year")
plt.ylabel("GDP $")
plt.legend(["Bahrain", "Kuwait", "Oman", "Saudi Arabia"])
plt.show()

#plt.subplot(326)
plt.plot(bhr_df.Year, bhr_df.GNI)
plt.plot(kwt_df.Year, kwt_df.GNI)
plt.plot(omn_df.Year, omn_df.GNI)
plt.plot(bhr_df.Year, bhr_df.GNI)
plt.plot(sar_df.Year, sar_df.GNI)
plt.title("Gross national income")
plt.xlabel("Year")
plt.ylabel("GNI")
plt.legend(["Bahrain", "Kuwait", "Oman", "Saudi Arabia"])
plt.show()

# GDP
plt.plot(bhr_df.Year, bhr_df.GDP_USD)
plt.plot(kwt_df.Year, kwt_df.GDP_USD)
plt.plot(omn_df.Year, omn_df.GDP_USD)
plt.plot(bhr_df.Year, bhr_df.GDP_USD)
plt.plot(sar_df.Year, sar_df.GDP_USD)
plt.title("Gross Domestic Product")
plt.xlabel("Year")
plt.ylabel("GDP")
plt.legend(["Bahrain", "Kuwait", "Oman", "Saudi Arabia"])
plt.show()